cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

hubble:
  relay:
    enabled: false
  ui:
    enabled: false

ipv6:
  enabled: true

ipam:
  mode: kubernetes

k8sServiceHost: localhost
k8sServicePort: 7445

kubeProxyReplacement: true

gatewayAPI:
  enabled: true
  hostNetwork:
    enabled: true

securityContext:
  privileged: true
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE