apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  parentRefs:
    - name: argocd-gateway
      sectionName: tls-passthrough
  hostnames:
    - "argocd.max-kubes.com"
  rules:
    - backendRefs:
      - name: argocd-server
        port: 443
