project: default
source:
  repoURL: git@github.com:lamtnguyen989/max-kubes.git
  path: kubevirt/cdi/
  targetRevision: HEAD
  directory:
    recurse: true
    jsonnet: {}
destination:
  server: https://kubernetes.default.svc
  namespace: cdi
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    enabled: true
  syncOptions:
    - CreateNamespace=true
