apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    path: IaC/cert-manager
    repoURL: git@github.com:lamtnguyen989/max-kubes.git
    targetRevision: HEAD
    directory:
      recurse: true
      include: "*.yaml"
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      enabled: true

