apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-operator
  namespace: argocd
spec:
  destination:
    namespace: inteldeviceplugins-system
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://intel.github.io/helm-charts 
      chart: intel-device-plugins-operator
      targetRevision: 0.37.1
      helm:
        valueFiles:
          - $values/IaC/intel-device-operator/values.yaml
    - repoURL: https://intel.github.io/helm-charts 
      chart: intel-device-plugins-gpu
      targetRevision: 0.37.1
      helm:
        valueFiles:
          - $values/IaC/intel-device-operator/values.yaml
    - repoURL: https://intel.github.io/helm-charts 
      chart: intel-device-plugins-npu
      targetRevision: 0.37.1
      helm:
        valueFiles:
          - $values/IaC/intel-device-operator/values.yaml
    - repoURL: git@github.com:lamtnguyen989/max-kubes.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:lamtnguyen989/max-kubes.git
      targetRevision: HEAD
      path: IaC/intel-device-operator
      directory:
        recurse: true
        include: "*.yaml"
        exclude: "values.yaml"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
