apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: argocd
spec:
  destination:
    namespace: node-feature-discovery
    server: https://kubernetes.default.svc
  sources:
    - repoURL: 
      chart: nfd
      targetRevision: 0.19.0
      helm:
        valueFiles:
          - $values/IaC/system/node-feature-discovery/values.yaml
    - repoURL: git@github.com:lamtnguyen989/max-kubes.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:lamtnguyen989/max-kubes.git
      targetRevision: HEAD
      path: IaC/system/node-feature-discovery
      directory:
        recurse: true
        include: "*.yaml"
        exclude: values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
