apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-desktop-25-04-dv
  namespace: virtual-machines
spec:
  source:
    http:
      url: "https://mirror.pilotfiber.com/ubuntu-iso/25.04/ubuntu-25.04-desktop-amd64.iso"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 7Gi
    storageClassName: longhorn