apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uwu-buntu-pvc
  namespace: virtual-machines
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: uwu-buntu-vm
  namespace: virtual-machines
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: uwu-buntu-vm
    spec:
      domain:
        devices:
          disks:
          - name: ubuntu-desktop-24-04-dv
            cdrom:
              bus: sata
            bootOrder: 1
          - name: harddisk
            disk:
              bus: virtio
            bootOrder: 2
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        machine:
          type: ""
        resources:
          requests:
            memory: 16Gi
            cpu: 4
      networks:
      - name: default
        pod: {}
      volumes:
      - name: ubuntu-desktop-24-04-dv
        dataVolume:
          name: ubuntu-desktop-24-04-dv
      - name: harddisk
        persistentVolumeClaim:
          claimName: uwu-buntu-pvc
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            package_update: true
            packages:
              - curl