---
prometheus:
  prometheusSpec:
    retention: 15d
    retentionSize: "20GiB"
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
grafana:
  "grafana.ini":
    server:
      protocol: https
      cert_file: /etc/grafana/tls/tls.crt
      cert_key: /etc/grafana/tls/tls.key
  extraSecretMounts:
    - name: grafana-tls
      secretName: grafana-dashboard-tls
      mountPath: /etc/grafana/tls
      readOnly: true
  livenessProbe:
    httpGet:
      path: /api/health
      port: 3000
      scheme: HTTPS
  readinessProbe:
    httpGet:
      path: /api/health
      port: 3000
      scheme: HTTPS
  service:
    port: 443
    targetPort: 3000
  serviceMonitor:
    enabled: true
    scheme: https
    tlsConfig:
      ca:
        secret:
          name: max-kubes-ca-secret
          key: ca.crt
