apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iac
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lamtnguyen989/max-kubes.git
    targetRevision: HEAD
    path: IaC/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
